workflows:
  expo-workflow:
    name: Expo Android Build
    environment:
      vars:
        EXPO_TOKEN: 7xV120ZpQsOnPJd6ST1MnZCDcJSaLAxqn5Ux3T6t
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli
      - name: Build APK with Expo EAS
        script: |
          eas build --platform android --non-interactive --profile preview
    artifacts:
      - build/**/*
    publishing:
      email:
        recipients:
          - pinakofficial44@gmail.com
