workflows:
  react-native-workflow:
    name: React Native APK Build
    max_build_duration: 60
    environment:
      vars:
        NODE_VERSION: 16.20.0
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
