workflows:
  expo-workflow:
    name: Expo Android Build
    environment:
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android app with Expo
        script: |
          npx expo install
          npx expo export --platform android
          npx eas-cli build --platform android --non-interactive --profile preview
    artifacts:
      - build/**/*.apk
    publishing:
      email:
        recipients:
          - pinakofficial44@gmail.com
